services: # 실행할 컨테이너 목록 정의
  app:
    build: .
    container_name: first_nest
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
      GISTORY_CLIENT_ID: ${GISTORY_CLIENT_ID}
      GISTORY_CLIENT_SECRET: ${GISTORY_CLIENT_SECRET}
      GISTORY_AUTHORIZE_URL: ${GISTORY_AUTHORIZE_URL}
      GISTORY_TOKEN_URL: ${GISTORY_TOKEN_URL}
      GISTORY_USERINFO_URL: ${GISTORY_USERINFO_URL}
      GISTORY_CALLBACK_URL: ${GISTORY_CALLBACK_URL}
      GISTORY_SCOPES: ${GISTORY_SCOPES}
      GISTORY_CODE_CHALLENGE: ${GISTORY_CODE_CHALLENGE}
    depends_on:
      - postgres
  postgres: # 서비스 이름 설정하는거
    image: postgres:16 # 도커 허브에서 16버전 이미지 사용
    container_name: nest_postgres # 컨테이너 이름 (docker ps 에서 나오는 이름)
    ports: # 호스트:컨테이너 포트 매핑 / 여기선 내 호스트 5432포트 - 컨테이너 5432포트 끼리 매핑한거
      - '5432:5432'
    environment: # 환경변수 설정
      POSTGRES_DB: ${POSTGRES_DB} # 생성할 데이터베이스 이름
      POSTGRES_USER: ${POSTGRES_USER} #} # DB 접속 유저 이름
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # DB 접속 유저 비밀번호
    volumes:
      - postgres_data:/var/lib/postgresql/data # 컨테이너 재시작해도 데이터 유지되게끔 볼륨에 저장

volumes:
  postgres_data: # 도커가 위에서 사용된 볼륨을 관리하도록 선언하는거
